package httpapi

import (
	"net"
	"net/http"
	"net/url"
	"strings"

	"github.com/divineshedrack33220/mailgeko/backend/internal/analytics"
	"github.com/divineshedrack33220/mailgeko/backend/internal/track"
)

var transparentPixel = []byte{
	0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00,
	0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x21,
	0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00,
	0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x02, 0x02,
	0x44, 0x01, 0x00, 0x3b,
}

func trackParams(r *http.Request) (campaignID, contactID, workspaceID string) {
	return r.URL.Query().Get("c"), r.URL.Query().Get("m"), r.URL.Query().Get("w")
}

// verifyTrackSignature rejects links that were not generated by this server,
// which prevents forged opens/clicks and open redirects. Parts are the
// campaign id, contact id and (for clicks) the raw target URL.
func (s *Server) verifyTrackSignature(r *http.Request, kind string, parts ...string) bool {
	return track.Valid(s.trackingSecret, kind, r.URL.Query().Get("s"), parts...)
}

// clientIP extracts the caller address using the trusted-proxy aware resolver.
// Forwarded-identity headers are only honoured from trusted peers, so rate
// limits and event attribution cannot be spoofed by setting headers directly.
func (s *Server) clientIP(r *http.Request) string {
	if s.trustedProxies != nil {
		return s.trustedProxies.clientIPFor(r)
	}
	// Fall back to the remote address when the server has no proxy config.
	if host, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return host
	}
	return r.RemoteAddr
}

func (s *Server) enqueueTrackEvent(r *http.Request, campaignID, contactID, workspaceID, eventType, url string) {
	if campaignID == "" || contactID == "" {
		return
	}
	if workspaceID == "" && s.db != nil {
		ws := ""
		if c, err := s.db.GetCampaignByID(r.Context(), campaignID); err == nil {
			ws = c.WorkspaceID
		}
		workspaceID = ws
	}

	dev := analytics.DetectDevice(r.UserAgent())
	countryCode := strings.TrimSpace(r.Header.Get("CF-IPCountry"))

	_ = s.queue.EnqueueRecordEvent(r.Context(), queueRecordEventPayload{
		WorkspaceID: workspaceID,
		CampaignID:  campaignID,
		ContactID:   contactID,
		Type:        eventType,
		URL:         url,
		Device:      dev.Name,
		Platform:    dev.Platform,
		Country:     analytics.CountryName(countryCode),
		CountryCode: countryCode,
		UserAgent:   r.UserAgent(),
		IP:          s.clientIP(r),
	})
}

func (s *Server) handleTrackOpen(w http.ResponseWriter, r *http.Request) {
	campaignID, contactID, workspaceID := trackParams(r)
	if !s.verifyTrackSignature(r, "open", campaignID, contactID) {
		http.NotFound(w, r)
		return
	}
	s.enqueueTrackEvent(r, campaignID, contactID, workspaceID, "opened", "")
	w.Header().Set("Content-Type", "image/gif")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(transparentPixel)
}

func (s *Server) handleTrackClick(w http.ResponseWriter, r *http.Request) {
	campaignID, contactID, workspaceID := trackParams(r)
	target := r.URL.Query().Get("u")
	if target == "" {
		http.NotFound(w, r)
		return
	}
	if !s.verifyTrackSignature(r, "click", campaignID, contactID, target) {
		http.NotFound(w, r)
		return
	}
	// Only redirect to http(s) targets; never allow javascript:, data:, etc.
	u, err := url.Parse(target)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") {
		http.NotFound(w, r)
		return
	}
	s.enqueueTrackEvent(r, campaignID, contactID, workspaceID, "clicked", target)
	http.Redirect(w, r, target, http.StatusFound)
}

func (s *Server) handleTrackUnsubscribe(w http.ResponseWriter, r *http.Request) {
	campaignID, contactID, workspaceID := trackParams(r)
	if !s.verifyTrackSignature(r, "unsubscribe", campaignID, contactID) {
		http.NotFound(w, r)
		return
	}
	s.enqueueTrackEvent(r, campaignID, contactID, workspaceID, "unsubscribed", "")
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte("<!doctype html><html><body><h2>You've been unsubscribed.</h2><p>You won't receive further emails from this sender.</p></body></html>"))
}
