-- Mailgeko sending defaults (TiDB / MySQL compatible)

ALTER TABLE workspaces
    ADD COLUMN IF NOT EXISTS from_name VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS from_email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reply_to VARCHAR(255) NOT NULL DEFAULT '';
