package engine

import (
	"context"
	"encoding/csv"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"github.com/divineshedrack33220/mailgeko/backend/internal/store"
)

var knownContactFields = map[string]bool{
	"email": true, "first_name": true, "firstname": true, "last_name": true, "lastname": true,
	"company": true, "position": true, "job_title": true, "country": true, "city": true,
	"phone": true, "phone_number": true, "phonenumber": true, "status": true, "tags": true,
}

func (e *Engine) ImportCSV(ctx context.Context, workspaceID, listID, path string) (imported, updated int64, err error) {
	// The worker trusts the queued payload, but the list ownership is verified
	// again here so a mis-issued or tampered task can never dump contacts into
	// another workspace's list.
	if listID != "" {
		if _, err := e.store.GetList(ctx, workspaceID, listID); err != nil {
			return 0, 0, fmt.Errorf("import: list %q does not exist in workspace %q", listID, workspaceID)
		}
	}
	// #nosec G304 -- path is server-generated by the import handler (os.TempDir()
	// + random hex); it is never derived from request input.
	f, err := os.Open(path)
	if err != nil {
		return 0, 0, err
	}
	defer f.Close()
	defer os.Remove(path)

	reader := csv.NewReader(f)
	reader.FieldsPerRecord = -1

	header, err := reader.Read()
	if err != nil {
		return 0, 0, err
	}
	colIndex := make(map[string]int, len(header))
	for i, h := range header {
		colIndex[normalizeHeader(h)] = i
	}

	// Load welcome automations once so bulk imports don't re-query them for
	// every imported contact.
	var welcome []*store.Automation
	if automations, err := e.store.ListAutomations(ctx, workspaceID); err != nil {
		log.Printf("import: list automations for welcome enrollment: %v", err)
	} else {
		welcome = filterWelcomeAutomations(automations)
	}

	var importErr error
	for {
		row, err := reader.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			importErr = err
			break
		}

		get := func(names ...string) string {
			for _, n := range names {
				if i, ok := colIndex[normalizeHeader(n)]; ok && i < len(row) {
					return strings.TrimSpace(row[i])
				}
			}
			return ""
		}

		email := get("email")
		if email == "" {
			continue
		}

		custom := make(map[string]string)
		var tags []string
		for rawHeader, i := range colIndex {
			if i >= len(row) {
				continue
			}
			val := strings.TrimSpace(row[i])
			if rawHeader == "tags" {
				tags = splitTags(val)
				continue
			}
			if knownContactFields[rawHeader] || val == "" {
				continue
			}
			custom[rawHeader] = val
		}

		status := get("status")
		if status == "" {
			status = store.ContactActive
		}

		contact := &store.Contact{
			ID:           NewID(),
			WorkspaceID:  workspaceID,
			Email:        strings.ToLower(email),
			FirstName:    get("first_name", "firstname"),
			LastName:     get("last_name", "lastname"),
			Company:      get("company"),
			Position:     get("position", "job_title"),
			Country:      get("country"),
			City:         get("city"),
			PhoneNumber:  get("phone_number", "phone", "phonenumber"),
			CustomFields: custom,
			Tags:         tags,
			Status:       status,
		}

		existing, err := e.store.ContactByEmail(ctx, workspaceID, contact.Email)
		if err == nil {
			contact.ID = existing.ID
			// Merge, never overwrite wholesale: a partial re-import that only
			// provides some columns must not wipe the fields and tags the
			// contact already had. Values present in the CSV win; anything the
			// CSV doesn't mention is preserved.
			if len(contact.CustomFields) == 0 {
				contact.CustomFields = existing.CustomFields
			} else {
				for k, v := range existing.CustomFields {
					if _, ok := contact.CustomFields[k]; !ok {
						contact.CustomFields[k] = v
					}
				}
			}
			if len(contact.Tags) == 0 {
				contact.Tags = existing.Tags
			} else {
				seen := make(map[string]bool, len(contact.Tags)+len(existing.Tags))
				for _, t := range contact.Tags {
					seen[t] = true
				}
				for _, t := range existing.Tags {
					if !seen[t] {
						contact.Tags = append(contact.Tags, t)
						seen[t] = true
					}
				}
			}
			if err := e.store.UpdateContact(ctx, contact); err != nil {
				return imported, updated, err
			}
			updated++
		} else if err := e.store.CreateContact(ctx, contact); err != nil {
			return imported, updated, err
		} else {
			imported++
			e.enrollWelcome(ctx, contact, welcome)
		}

		if listID != "" {
			_ = e.store.AddContactToList(ctx, listID, contact.ID)
		}
	}

	if importErr != nil {
		return imported, updated, importErr
	}
	return imported, updated, nil
}

func normalizeHeader(h string) string {
	return strings.ToLower(strings.ReplaceAll(strings.TrimSpace(h), " ", "_"))
}

func splitTags(v string) []string {
	var out []string
	for _, part := range strings.Split(v, ",") {
		if t := strings.TrimSpace(part); t != "" {
			out = append(out, t)
		}
	}
	return out
}
