// Package track signs and verifies the query strings used by email tracking
// links (opens, clicks, unsubscribes). A valid signature proves the link was
// generated by the server, which prevents forged engagement events and blocks
// tracking URLs from being abused as open redirects.
package track

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
)

// Sign returns a hex-encoded HMAC-SHA256 of the kind and parts, keyed by the
// server's tracking secret.
func Sign(secret, kind string, parts ...string) string {
	h := hmac.New(sha256.New, []byte(secret))
	h.Write([]byte(kind))
	for _, p := range parts {
		h.Write([]byte{0})
		h.Write([]byte(p))
	}
	return hex.EncodeToString(h.Sum(nil))
}

// Valid reports whether provided is a constant-time-equal match for the
// signature of kind and parts under the given secret.
func Valid(secret, kind, provided string, parts ...string) bool {
	if secret == "" || provided == "" {
		return false
	}
	return hmac.Equal([]byte(provided), []byte(Sign(secret, kind, parts...)))
}
